providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_18", "pnpm", "pkg-config", "glib", "gtk3", "webkitgtk", "openssl", "librsvg", "libsoup"]

[phases.install]
cmds = ["pnpm install --filter @gns/web..."]

[phases.build]
cmds = ["pnpm --filter @gns/web build"]

[start]
cmd = "cd apps/web && pnpm run start:prod"
