

[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile --filter @gns/web..."]

[phases.build]
cmds = ["pnpm --filter @gns/web... build"]

[start]
cmd = "cd apps/web && pnpm run start:prod"
